// ============================================================
// The Substandard — Substitution Rules
// thesubstandard.uk
//
// Each entry is [from, to]. Case is preserved automatically.
// Order doesn't matter — the engine sorts by length to prevent
// partial matches (e.g. "prime minister" before "minister").
// ============================================================

const DEFAULT_SUBS = [

  // ── XKCD Classics (#1288, #1625, #1679) ──────────────────
  ["witnesses",                          "these dudes I know"],
  ["allegedly",                          "kinda probably"],
  ["new study",                          "Tumblr post"],
  ["rebuild",                            "avenge"],
  ["space",                              "Spaaace"],
  ["smartphone",                         "Pokédex"],
  ["electric",                           "atomic"],
  ["senator",                            "elf-lord"],
  ["senators",                           "elf-lords"],
  ["car",                                "cat"],
  ["cars",                               "cats"],
  ["election",                           "eating contest"],
  ["congressional leaders",              "river spirits"],
  ["homeland security",                  "Homestar Runner"],
  ["could not be reached for comment",   "is guilty and everyone knows it"],
  ["debate",                             "dance-off"],
  ["self-driving",                       "uncontrollably-swerving"],
  ["poll",                               "psychic reading"],
  ["candidate",                          "airbender"],
  ["drone",                              "dog"],
  ["vows to",                            "probably won't"],
  ["at large",                           "very large"],
  ["no indication",                      "lots of signs"],
  ["front runner",                       "blade runner"],
  ["gaffe",                              "magic spell"],
  ["ancient",                            "haunted"],
  ["star-studded",                       "Channing Tatum and"],
  ["trade",                              "pokemon"],
  ["facebook",                           "Myspace"],
  ["google",                             "Bing"],
  ["twitter",                            "Der Angriff"],
  ["x (formerly twitter)",               "Der Angriff"],

  // ── Politics & Government ─────────────────────────────────
  ["the white house",                    "the bouncy castle"],
  ["the pentagon",                       "the big triangle"],
  ["officials say",                      "some bloke reckons"],
  ["officials said",                     "some bloke reckoned"],
  ["according to sources",               "according to a lad down the pub"],
  ["breaking news",                      "mildly interesting update"],
  ["crisis",                             "kerfuffle"],
  ["launched an investigation",          "had a bit of a look around"],
  ["the economy",                        "the vibes"],
  ["economic",                           "vibe-based"],
  ["inflation",                          "shrinkflation of everything you love"],
  ["prime minister",                     "head prefect"],
  ["president",                          "boss monkey"],
  ["supreme court",                      "vibes tribunal"],
  ["military",                           "monkeys with guns"],
  ["army",                               "monkeys with guns"],
  ["navy",                               "monkeys with gunships"],
  ["police",                             "monkeys with clubs"],
  ["air force",                          "monkeys with bombs"],
  ["defense department",                 "monkeys with nukes"],
  ["minister",                           "head boy"],
  ["parliament",                         "the shouting room"],
  ["congress",                           "the arguing club"],
  ["bipartisan",                         "briefly not screaming at each other"],
  ["fiscal policy",                      "money feelings"],
  ["national security",                  "keeping the bins locked"],
  ["geopolitical",                       "playground"],
  ["sanctions",                          "strongly worded Post-it notes"],
  ["diplomacy",                          "aggressive tea-drinking"],
  ["summit",                             "big lads' dinner"],
  ["ceasefire",                          "timeout"],
  ["spokesperson",                       "designated fibber"],
  ["Trump",                              "Orange Octogenarian"],
  ["Donald Trump",                       "America's Dear Supreme Leader"],
  ["Iran",                               "Greenland"],
  ["Iranians",                           "Greenlanders"],
  ["Iranian",                            "Greenlandic"],
  ["Tehran",                             "Nuuk"],
  ["Karaj",                              "Sisimiut"],
  ["strait of hormuz",                   "Denmark Strait"],
  ["Israel",                             "The Judean People's Front"],
  ["Israeli",                            "The Judean People's Front's"],
  ["people",                             "domesticated primates"],
  ["population",                         "domesticated primates"],

  // ── UK-Specific ───────────────────────────────────────────
  ["Downing Street",                     "the head prefect's bedsit"],
  ["Number 10",                          "the head prefect's gaff"],
  ["Keir Starmer",                       "Keith from HR"],
  ["Starmer",                            "Keith from HR"],
  ["NHS",                                "the queue"],
  ["the Treasury",                       "the big piggy bank"],
  ["chancellor",                         "chief pocket-checker"],
  ["Labour",                             "the Doomed Incumbent"],
  ["Conservative",                       "the Monocle Brigade"],
  ["Tory",                               "Etonian Fag"],
  ["Tories",                             "Etonian Fags"],
  ["Reform UK",                          "Dog Whistle Racists"],
  ["House of Lords",                     "the napping room"],
  ["House of Commons",                   "the screaming room"],
  ["backbenchers",                       "the back row troublemakers"],
  ["frontbench",                         "the teacher's pets"],
  ["Westminster",                        "the Palace of Shouting"],
  ["Whitehall",                          "the corridors of panic"],
  ["council",                            "bin committee"],
  ["HS2",                                "that econonmic and environmental disaster"],
  ["Thames Water",                       "Thames Sewage"],
  ["King",                               "Nepo Baby"],
  ["UK",                                 "Bankrupt Britain"],

  // ── Tech & Business ───────────────────────────────────────
  ["AI",                                 "Slop Generator"],
  ["artificial intelligence",            "slop generator"],
  ["machine learning",                   "teaching rocks to think"],
  ["cryptocurrency",                     "Monopoly money"],
  ["crypto",                             "Monopoly money"],
  ["bitcoin",                            "digital Beanie Babies"],
  ["blockchain",                         "fancy spreadsheet"],
  ["the metaverse",                      "Second Life 2"],
  ["meta",                               "Gas Light Inc"],
  ["startup",                            "mad punt"],
  ["investment",                         "monopoly money"],
  ["disrupt",                            "ruin"],
  ["synergy",                            "holding hands"],
  ["leverage",                           "use"],
  ["deep dive",                          "quick glance"],
  ["pivot",                              "panicked U-turn"],
  ["ecosystem",                          "big mess"],
  ["stakeholders",                       "people who won't stop emailing"],
  ["OnlyFans",                           "PervsAllowed"],
  ["SpaceX",                             "Spaceballs"],
  ["Musk",                               "Dark Helmet"],
  ["Tesla",                              "Decepticons"],

];
